import 'package:flutter/material.dart';
const MaterialColor green = Colors.green;
final Color orangeShade900 = Colors.orange.shade900;
final Color orangeShade800 = Colors.orange.shade800;
final Color orangeShade400 = Colors.orange.shade400;
const Color white = Colors.white;
const Color kahve = Color.fromRGBO(225, 95, 27, .3);
final Color greySheed200 = Colors.grey.shade200;
const Color grey = Colors.grey;
final  Color? orange900 = Colors.orange[900];
final  Color? orange400 = Colors.orange[400];
const Color red = Colors.red;
