// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa7HeSFAVoJRYVQJ75hdamOg4o4QK-cIQ',
    appId: '1:91213610411:web:d025a1386dbe516a3366ee',
    messagingSenderId: '91213610411',
    projectId: 'yyu-harita-app',
    authDomain: 'yyu-harita-app.firebaseapp.com',
    storageBucket: 'yyu-harita-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiyVu5_YahsiUT3JkiaeSHmESvLLNC8Es',
    appId: '1:91213610411:android:1b0c6cda9353fa153366ee',
    messagingSenderId: '91213610411',
    projectId: 'yyu-harita-app',
    storageBucket: 'yyu-harita-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHT2QHfJAp9S1Nto19L6Meo80LlUq5TwI',
    appId: '1:91213610411:ios:cc82cec623763d7e3366ee',
    messagingSenderId: '91213610411',
    projectId: 'yyu-harita-app',
    storageBucket: 'yyu-harita-app.appspot.com',
    iosBundleId: 'com.example.haritaUygulamaYyu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHT2QHfJAp9S1Nto19L6Meo80LlUq5TwI',
    appId: '1:91213610411:ios:cc82cec623763d7e3366ee',
    messagingSenderId: '91213610411',
    projectId: 'yyu-harita-app',
    storageBucket: 'yyu-harita-app.appspot.com',
    iosBundleId: 'com.example.haritaUygulamaYyu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa7HeSFAVoJRYVQJ75hdamOg4o4QK-cIQ',
    appId: '1:91213610411:web:bcda87355b104fd23366ee',
    messagingSenderId: '91213610411',
    projectId: 'yyu-harita-app',
    authDomain: 'yyu-harita-app.firebaseapp.com',
    storageBucket: 'yyu-harita-app.appspot.com',
  );

}